# the BioSample accession
biosample_accession: ?

# name of CSV file listing barcode runs to uploade
barcode_runs: ../data/barcode_runs.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/jbloom_fhcrc.org_IuMBgK44

# Meaningful name for this sample's FTP folder:
ftp_subfolder: Ellebedy_in_vivo_antibody_barcodes
